**MMT Project**

Statistical Tests: Student's t-Test & Wilcoxon's Signed Rank Test

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

plt.style.use('seaborn')

<ipython-input-1-047b86b25348>:7: MatplotlibDeprecationWarning: The seaborn styles shipped by Matplotlib are deprecated since 3.6, as they no longer correspond to the styles shipped by seaborn. However, they will remain available as 'seaborn-v0_8-<style>'. Alternatively, directly use the seaborn API instead.
  plt.style.use('seaborn')

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
df = pd.read_csv('/content/drive/MyDrive/No_music_MMT.csv',sep='|')
df_white = pd.read_csv('/content/drive/MyDrive/White_noise_MMT.csv',sep='|')
df_music = pd.read_csv('/content/drive/MyDrive/Music_original_MMT.csv',sep='|')
df_incr = pd.read_csv('/content/drive/MyDrive/Increased_tempo_MMT.csv',sep='|')

In [4]:
df.head()

,_id,isPb,wpm,acc,rawWpm,consistency,charStats,mode,mode2,quoteLength,...,punctuation,numbers,language,funbox,difficulty,lazyMode,blindMode,bailedOut,tags,timestamp
0,643bff54b32f409c529023e8,NaN,55.13,96.49,57.86,70.42,"827,11,2,0",time,180,-1,...,False,False,english,none,normal,False,False,False,NaN,1681653588000
1,643bf72fb32f409c5283d176,NaN,47.60,88.57,56.00,63.04,"714,42,7,7",time,180,-1,...,False,False,english,none,normal,False,False,False,NaN,1681651503000
2,643bf578b32f409c5283c493,NaN,65.33,94.64,65.33,69.14,"980,0,0,0",time,180,-1,...,False,False,english,none,normal,False,False,False,NaN,1681651064000
3,643bf04ab32f409c52778b57,NaN,55.86,94.63,56.20,70.22,"838,0,0,1",time,180,-1,...,False,False,english,none,normal,False,False,False,NaN,1681649738000
4,643bdca5b32f409c5258ced9,NaN,76.53,91.80,76.80,60.79,"1148,2,0,1",time,180,-1,...,False,False,english,none,normal,False,False,False,NaN,1681644709000

In [5]:
df.columns

Index(['_id', 'isPb', 'wpm', 'acc', 'rawWpm', 'consistency', 'charStats',
       'mode', 'mode2', 'quoteLength', 'restartCount', 'testDuration',
       'afkDuration', 'incompleteTestSeconds', 'punctuation', 'numbers',
       'language', 'funbox', 'difficulty', 'lazyMode', 'blindMode',
       'bailedOut', 'tags', 'timestamp'],
      dtype='object')

In [6]:
df = df.drop([ '_id','isPb','mode', 'mode2', 'quoteLength', 'restartCount', 'testDuration','afkDuration',
              'incompleteTestSeconds', 'punctuation', 'numbers','language', 'funbox', 'difficulty', 
              'lazyMode', 'blindMode','bailedOut', 'tags', 'timestamp'],axis = 1)

df_white = df_white.drop([ '_id','isPb','mode', 'mode2', 'quoteLength', 'restartCount', 'testDuration','afkDuration',
              'incompleteTestSeconds', 'punctuation', 'numbers','language', 'funbox', 'difficulty', 
              'lazyMode', 'blindMode','bailedOut', 'tags', 'timestamp'],axis = 1)

df_music = df_music.drop([ '_id','isPb','mode', 'mode2', 'quoteLength', 'restartCount', 'testDuration','afkDuration',
              'incompleteTestSeconds', 'punctuation', 'numbers','language', 'funbox', 'difficulty', 
              'lazyMode', 'blindMode','bailedOut', 'tags', 'timestamp'],axis = 1)

df_incr = df_incr.drop([ '_id','isPb','mode', 'mode2', 'quoteLength', 'restartCount', 'testDuration','afkDuration',
              'incompleteTestSeconds', 'punctuation', 'numbers','language', 'funbox', 'difficulty', 
              'lazyMode', 'blindMode','bailedOut', 'tags', 'timestamp'],axis = 1)

In [7]:
df.columns, df_white.columns, df_music.columns, df_incr.columns

(Index(['wpm', 'acc', 'rawWpm', 'consistency', 'charStats'], dtype='object'),
 Index(['wpm', 'acc', 'rawWpm', 'consistency', 'charStats'], dtype='object'),
 Index(['wpm', 'acc', 'rawWpm', 'consistency', 'charStats'], dtype='object'),
 Index(['wpm', 'acc', 'rawWpm', 'consistency', 'charStats'], dtype='object'))

In [8]:
# For no music
# split the string into four values using the split() method
split_values = df['charStats'].str.split(',')

# create four new columns in the dataframe and assign the split values to them
df['correct'] = split_values.str[0]
df['incorrect'] = split_values.str[1]
df['extra'] = split_values.str[2]
df['missed'] = split_values.str[3]

df = df.drop(['charStats'],axis=1)

# For white noise 
split_values = df_white['charStats'].str.split(',')

df_white['correct'] = split_values.str[0]
df_white['incorrect'] = split_values.str[1]
df_white['extra'] = split_values.str[2]
df_white['missed'] = split_values.str[3]

df_white = df_white.drop(['charStats'],axis=1)

# For music
split_values = df_music['charStats'].str.split(',')

df_music['correct'] = split_values.str[0]
df_music['incorrect'] = split_values.str[1]
df_music['extra'] = split_values.str[2]
df_music['missed'] = split_values.str[3]

df_music = df_music.drop(['charStats'],axis=1)

# For increased tempo
split_values = df_incr['charStats'].str.split(',')

df_incr['correct'] = split_values.str[0]
df_incr['incorrect'] = split_values.str[1]
df_incr['extra'] = split_values.str[2]
df_incr['missed'] = split_values.str[3]

df_incr = df_incr.drop(['charStats'],axis=1)

df_incr['correct'] = df_incr['correct'].astype(int)
df_incr['incorrect'] = df_incr['incorrect'].astype(int)
df_incr['extra'] = df_incr['extra'].astype(int)
df_incr['missed'] = df_incr['missed'].astype(int)

df['correct'] = df['correct'].astype(int)
df['incorrect'] = df['incorrect'].astype(int)
df['extra'] = df['extra'].astype(int)
df['missed'] = df['missed'].astype(int)

df_music['correct'] = df_music['correct'].astype(int)
df_music['incorrect'] = df_music['incorrect'].astype(int)
df_music['extra'] = df_music['extra'].astype(int)
df_music['missed'] = df_music['missed'].astype(int)

df_white['correct'] = df_white['correct'].astype(int)
df_white['incorrect'] = df_white['incorrect'].astype(int)
df_white['extra'] = df_white['extra'].astype(int)
df_white['missed'] = df_white['missed'].astype(int)

In [9]:
df.head(10)

     wpm    acc  rawWpm  consistency  correct  incorrect  extra  missed
0  55.13  96.49   57.86        70.42      827         11      2       0
1  47.60  88.57   56.00        63.04      714         42      7       7
2  65.33  94.64   65.33        69.14      980          0      0       0
3  55.86  94.63   56.20        70.22      838          0      0       1
4  76.53  91.80   76.80        60.79     1148          2      0       1
5  33.93  94.08   35.40        45.41      509          4      2       2
6  76.20  96.00   76.20        70.59     1143          0      0       0
7  41.40  94.85   43.80        58.93      621         10      3       4
8  72.27  93.81   72.27        64.06     1084          0      0       0
9  36.06  86.03   40.20        65.02      541         15      3       0

In [10]:
df_white.head()

     wpm    acc  rawWpm  consistency  correct  incorrect  extra  missed
0  53.73  97.62   55.33        64.94      806          5      1       0
1  48.60  92.44   52.93        69.99      729         22      4       2
2  65.33  93.53   65.40        69.62      980          1      0       0
3  49.67  90.66   49.93        66.24      745          1      0       0
4  84.33  94.51   84.93        68.44     1265          2      0       2

# Paired Student’s t-test

Tests whether the means of two paired samples are significantly different.

Assumptions

Observations in each sample are independent and identically distributed (iid).
Observations in each sample are normally distributed.
Observations in each sample have the same variance.
Observations across each sample are paired.
Interpretation

H0: the means of the samples are equal.

H1: the means of the samples are unequal.

In [11]:
# Paired Student's t-test
from scipy.stats import ttest_rel
test_params = ['wpm', 'acc', 'rawWpm', 'consistency', 'correct', 'extra', 'missed']
for param in test_params:
  print(param)
  no_music = df[param].to_numpy()
  white = df_white[param].to_numpy()
  music = df_music[param].to_numpy()
  incr = df_incr[param].to_numpy()
  # no_music v/s white, no_music v/s music, no_music v/s incr, white v/s music,
  # white v/s incr, music v/s incr
  stat, p = ttest_rel(no_music, white)
  print('no_music v/s', 'white')
  print('stat=%.3f, p=%.3f' % (stat, p))
  if p > 0.05:
    print('Probably the same distribution')
  else:
    print('Probably different distributions')
  stat, p = ttest_rel(no_music, music)
  print('no_music v/s', 'music')
  print('stat=%.3f, p=%.3f' % (stat, p))
  if p > 0.05:
    print('Probably the same distribution')
  else:
    print('Probably different distributions')
  stat, p = ttest_rel(no_music, incr)
  print('no_music v/s', 'incr')
  print('stat=%.3f, p=%.3f' % (stat, p))
  if p > 0.05:
    print('Probably the same distribution')
  else:
    print('Probably different distributions')
  stat, p = ttest_rel(white, music)
  print('white v/s', 'music')
  print('stat=%.3f, p=%.3f' % (stat, p))
  if p > 0.05:
    print('Probably the same distribution')
  else:
    print('Probably different distributions')
  stat, p = ttest_rel(white, incr)
  print('white v/s', 'incr')
  print('stat=%.3f, p=%.3f' % (stat, p))
  if p > 0.05:
    print('Probably the same distribution')
  else:
    print('Probably different distributions')
  stat, p = ttest_rel(music, incr)
  print('music v/s', 'incr')
  print('stat=%.3f, p=%.3f' % (stat, p))
  if p > 0.05:
    print('Probably the same distribution')
  else:
    print('Probably different distributions')
  print()

wpm
no_music v/s white
stat=0.821, p=0.419
Probably the same distribution
no_music v/s music
stat=0.166, p=0.869
Probably the same distribution
no_music v/s incr
stat=0.965, p=0.343
Probably the same distribution
white v/s music
stat=-0.647, p=0.523
Probably the same distribution
white v/s incr
stat=0.203, p=0.840
Probably the same distribution
music v/s incr
stat=0.885, p=0.383
Probably the same distribution

acc
no_music v/s white
stat=-0.432, p=0.669
Probably the same distribution
no_music v/s music
stat=-1.032, p=0.311
Probably the same distribution
no_music v/s incr
stat=0.032, p=0.975
Probably the same distribution
white v/s music
stat=-0.662, p=0.513
Probably the same distribution
white v/s incr
stat=0.363, p=0.719
Probably the same distribution
music v/s incr
stat=0.908, p=0.371
Probably the same distribution

rawWpm
no_music v/s white
stat=1.123, p=0.271
Probably the same distribution
no_music v/s music
stat=0.003, p=0.998
Probably the same distribution
no_music v/s incr
stat=0.868, p=0.392
Probably the same distribution
white v/s music
stat=-1.178, p=0.248
Probably the same distribution
white v/s incr
stat=-0.310, p=0.759
Probably the same distribution
music v/s incr
stat=0.801, p=0.430
Probably the same distribution

consistency
no_music v/s white
stat=0.971, p=0.340
Probably the same distribution
no_music v/s music
stat=0.107, p=0.916
Probably the same distribution
no_music v/s incr
stat=1.588, p=0.123
Probably the same distribution
white v/s music
stat=-0.830, p=0.413
Probably the same distribution
white v/s incr
stat=0.251, p=0.803
Probably the same distribution
music v/s incr
stat=0.956, p=0.347
Probably the same distribution

correct
no_music v/s white
stat=0.823, p=0.417
Probably the same distribution
no_music v/s music
stat=0.168, p=0.868
Probably the same distribution
no_music v/s incr
stat=0.964, p=0.343
Probably the same distribution
white v/s music
stat=-0.648, p=0.522
Probably the same distribution
white v/s incr
stat=0.200, p=0.843
Probably the same distribution
music v/s incr
stat=0.882, p=0.385
Probably the same distribution

extra
no_music v/s white
stat=1.355, p=0.186
Probably the same distribution
no_music v/s music
stat=0.283, p=0.779
Probably the same distribution
no_music v/s incr
stat=-0.052, p=0.959
Probably the same distribution
white v/s music
stat=-1.043, p=0.306
Probably the same distribution
white v/s incr
stat=-1.332, p=0.193
Probably the same distribution
music v/s incr
stat=-0.317, p=0.753
Probably the same distribution

missed
no_music v/s white
stat=-0.102, p=0.919
Probably the same distribution
no_music v/s music
stat=-1.280, p=0.211
Probably the same distribution
no_music v/s incr
stat=-0.093, p=0.927
Probably the same distribution
white v/s music
stat=-1.496, p=0.145
Probably the same distribution
white v/s incr
stat=0.000, p=1.000
Probably the same distribution
music v/s incr
stat=1.300, p=0.204
Probably the same distribution

# Wilcoxon's Signed Rank Test

Tests whether the distributions of two paired samples are equal or not.

Assumptions

Observations in each sample are independent and identically distributed (iid).
Observations in each sample can be ranked.
Observations across each sample are paired.
Interpretation

H0: the distributions of both samples are equal.
H1: the distributions of both samples are not equal.

In [ ]:
# Wilcoxon's Signed Rank Test
from scipy.stats import wilcoxon
test_params = ['wpm', 'acc', 'rawWpm', 'consistency', 'correct', 'extra', 'missed']
for param in test_params:
  print(param)
  no_music = df[param].to_numpy()
  white = df_white[param].to_numpy()
  music = df_music[param].to_numpy()
  incr = df_incr[param].to_numpy()
  # no_music v/s white, no_music v/s music, no_music v/s incr, white v/s music,
  # white v/s incr, music v/s incr
  stat, p = wilcoxon(no_music, white)
  print('no_music v/s', 'white')
  print('stat=%.3f, p=%.3f' % (stat, p))
  if p > 0.05:
    print('Probably the same distribution')
  else:
    print('Probably different distributions')
  stat, p = wilcoxon(no_music, music)
  print('no_music v/s', 'music')
  print('stat=%.3f, p=%.3f' % (stat, p))
  if p > 0.05:
    print('Probably the same distribution')
  else:
    print('Probably different distributions')
  stat, p = wilcoxon(no_music, incr)
  print('no_music v/s', 'incr')
  print('stat=%.3f, p=%.3f' % (stat, p))
  if p > 0.05:
    print('Probably the same distribution')
  else:
    print('Probably different distributions')
  stat, p = wilcoxon(white, music)
  print('white v/s', 'music')
  print('stat=%.3f, p=%.3f' % (stat, p))
  if p > 0.05:
    print('Probably the same distribution')
  else:
    print('Probably different distributions')
  stat, p = wilcoxon(white, incr)
  print('white v/s', 'incr')
  print('stat=%.3f, p=%.3f' % (stat, p))
  if p > 0.05:
    print('Probably the same distribution')
  else:
    print('Probably different distributions')
  stat, p = wilcoxon(music, incr)
  print('music v/s', 'incr')
  print('stat=%.3f, p=%.3f' % (stat, p))
  if p > 0.05:
    print('Probably the same distribution')
  else:
    print('Probably different distributions')
  print()

wpm
no_music v/s white
stat=186.500, p=0.503
Probably the same distribution
no_music v/s music
stat=222.000, p=0.839
Probably the same distribution
no_music v/s incr
stat=195.000, p=0.452
Probably the same distribution
white v/s music
stat=208.000, p=0.626
Probably the same distribution
white v/s incr
stat=207.000, p=0.612
Probably the same distribution
music v/s incr
stat=181.000, p=0.299
Probably the same distribution

acc
no_music v/s white
stat=209.000, p=0.641
Probably the same distribution
no_music v/s music
stat=180.500, p=0.289
Probably the same distribution
no_music v/s incr
stat=221.000, p=0.824
Probably the same distribution
white v/s music
stat=185.500, p=0.489
Probably the same distribution
white v/s incr
stat=224.500, p=0.887
Probably the same distribution
music v/s incr
stat=212.500, p=0.700
Probably the same distribution

rawWpm
no_music v/s white
stat=165.500, p=0.177
Probably the same distribution
no_music v/s music
stat=195.000, p=0.627
Probably the same distribution
no_music v/s incr
stat=198.000, p=0.490
Probably the same distribution
white v/s music
stat=165.000, p=0.171
Probably the same distribution
white v/s incr
stat=222.000, p=0.839
Probably the same distribution
music v/s incr
stat=193.000, p=0.428
Probably the same distribution

consistency
no_music v/s white
stat=183.500, p=0.328
Probably the same distribution
no_music v/s music
stat=222.000, p=0.839
Probably the same distribution
no_music v/s incr
stat=173.000, p=0.229
Probably the same distribution
white v/s music
stat=175.000, p=0.245
Probably the same distribution
white v/s incr
stat=222.000, p=0.839
Probably the same distribution
music v/s incr
stat=176.000, p=0.253
Probably the same distribution

correct
no_music v/s white
stat=186.500, p=0.503
Probably the same distribution
no_music v/s music
stat=221.500, p=0.824
Probably the same distribution
no_music v/s incr
stat=195.500, p=0.465
Probably the same distribution
white v/s music
stat=209.000, p=0.641
Probably the same distribution
white v/s incr
stat=207.000, p=0.612
Probably the same distribution
music v/s incr
stat=182.000, p=0.309
Probably the same distribution

extra
no_music v/s white
stat=41.500, p=0.169
Probably the same distribution
no_music v/s music
stat=109.000, p=0.819
Probably the same distribution
no_music v/s incr
stat=109.500, p=0.831
Probably the same distribution
white v/s music
stat=55.500, p=0.188
Probably the same distribution
white v/s incr
stat=56.500, p=0.113
Probably the same distribution
music v/s incr
stat=103.000, p=0.940
Probably the same distribution

missed
no_music v/s white
stat=82.500, p=0.894
Probably the same distribution
no_music v/s music
stat=123.500, p=0.440
Probably the same distribution
no_music v/s incr
stat=99.000, p=0.820
Probably the same distribution
white v/s music
stat=87.500, p=0.198
Probably the same distribution
white v/s incr
stat=66.000, p=0.917
Probably the same distribution
music v/s incr
stat=90.000, p=0.364
Probably the same distribution

/usr/local/lib/python3.9/dist-packages/scipy/stats/_morestats.py:3414: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "